# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.6

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Produce verbose output by default.
VERBOSE = 1

# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = "C:/Program Files/CMake/bin/cmake.exe"

# The command to remove a file.
RM = "C:/Program Files/CMake/bin/cmake.exe" -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = C:/Users/uri/GIT/modVer

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = C:/Users/uri/GIT/modVer

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	"C:/Program Files/CMake/bin/cmake-gui.exe" -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	"c:/Program Files/CMake/bin/cmake.exe" -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start C:/Users/uri/GIT/modVer/CMakeFiles C:/Users/uri/GIT/modVer/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start C:/Users/uri/GIT/modVer/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named modVer

# Build rule for target.
modVer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 modVer
.PHONY : modVer

# fast build rule for target.
modVer/fast:
	$(MAKE) -f CMakeFiles/modVer.dir/build.make CMakeFiles/modVer.dir/build
.PHONY : modVer/fast

src/common/Log.obj: src/common/Log.cpp.obj

.PHONY : src/common/Log.obj

# target to build an object file
src/common/Log.cpp.obj:
	$(MAKE) -f CMakeFiles/modVer.dir/build.make CMakeFiles/modVer.dir/src/common/Log.cpp.obj
.PHONY : src/common/Log.cpp.obj

src/common/Log.i: src/common/Log.cpp.i

.PHONY : src/common/Log.i

# target to preprocess a source file
src/common/Log.cpp.i:
	$(MAKE) -f CMakeFiles/modVer.dir/build.make CMakeFiles/modVer.dir/src/common/Log.cpp.i
.PHONY : src/common/Log.cpp.i

src/common/Log.s: src/common/Log.cpp.s

.PHONY : src/common/Log.s

# target to generate assembly for a file
src/common/Log.cpp.s:
	$(MAKE) -f CMakeFiles/modVer.dir/build.make CMakeFiles/modVer.dir/src/common/Log.cpp.s
.PHONY : src/common/Log.cpp.s

src/frontend/boogie/coco/Parser.obj: src/frontend/boogie/coco/Parser.cpp.obj

.PHONY : src/frontend/boogie/coco/Parser.obj

# target to build an object file
src/frontend/boogie/coco/Parser.cpp.obj:
	$(MAKE) -f CMakeFiles/modVer.dir/build.make CMakeFiles/modVer.dir/src/frontend/boogie/coco/Parser.cpp.obj
.PHONY : src/frontend/boogie/coco/Parser.cpp.obj

src/frontend/boogie/coco/Parser.i: src/frontend/boogie/coco/Parser.cpp.i

.PHONY : src/frontend/boogie/coco/Parser.i

# target to preprocess a source file
src/frontend/boogie/coco/Parser.cpp.i:
	$(MAKE) -f CMakeFiles/modVer.dir/build.make CMakeFiles/modVer.dir/src/frontend/boogie/coco/Parser.cpp.i
.PHONY : src/frontend/boogie/coco/Parser.cpp.i

src/frontend/boogie/coco/Parser.s: src/frontend/boogie/coco/Parser.cpp.s

.PHONY : src/frontend/boogie/coco/Parser.s

# target to generate assembly for a file
src/frontend/boogie/coco/Parser.cpp.s:
	$(MAKE) -f CMakeFiles/modVer.dir/build.make CMakeFiles/modVer.dir/src/frontend/boogie/coco/Parser.cpp.s
.PHONY : src/frontend/boogie/coco/Parser.cpp.s

src/frontend/boogie/coco/Scanner.obj: src/frontend/boogie/coco/Scanner.cpp.obj

.PHONY : src/frontend/boogie/coco/Scanner.obj

# target to build an object file
src/frontend/boogie/coco/Scanner.cpp.obj:
	$(MAKE) -f CMakeFiles/modVer.dir/build.make CMakeFiles/modVer.dir/src/frontend/boogie/coco/Scanner.cpp.obj
.PHONY : src/frontend/boogie/coco/Scanner.cpp.obj

src/frontend/boogie/coco/Scanner.i: src/frontend/boogie/coco/Scanner.cpp.i

.PHONY : src/frontend/boogie/coco/Scanner.i

# target to preprocess a source file
src/frontend/boogie/coco/Scanner.cpp.i:
	$(MAKE) -f CMakeFiles/modVer.dir/build.make CMakeFiles/modVer.dir/src/frontend/boogie/coco/Scanner.cpp.i
.PHONY : src/frontend/boogie/coco/Scanner.cpp.i

src/frontend/boogie/coco/Scanner.s: src/frontend/boogie/coco/Scanner.cpp.s

.PHONY : src/frontend/boogie/coco/Scanner.s

# target to generate assembly for a file
src/frontend/boogie/coco/Scanner.cpp.s:
	$(MAKE) -f CMakeFiles/modVer.dir/build.make CMakeFiles/modVer.dir/src/frontend/boogie/coco/Scanner.cpp.s
.PHONY : src/frontend/boogie/coco/Scanner.cpp.s

src/frontend/parser/ParserBase.obj: src/frontend/parser/ParserBase.cpp.obj

.PHONY : src/frontend/parser/ParserBase.obj

# target to build an object file
src/frontend/parser/ParserBase.cpp.obj:
	$(MAKE) -f CMakeFiles/modVer.dir/build.make CMakeFiles/modVer.dir/src/frontend/parser/ParserBase.cpp.obj
.PHONY : src/frontend/parser/ParserBase.cpp.obj

src/frontend/parser/ParserBase.i: src/frontend/parser/ParserBase.cpp.i

.PHONY : src/frontend/parser/ParserBase.i

# target to preprocess a source file
src/frontend/parser/ParserBase.cpp.i:
	$(MAKE) -f CMakeFiles/modVer.dir/build.make CMakeFiles/modVer.dir/src/frontend/parser/ParserBase.cpp.i
.PHONY : src/frontend/parser/ParserBase.cpp.i

src/frontend/parser/ParserBase.s: src/frontend/parser/ParserBase.cpp.s

.PHONY : src/frontend/parser/ParserBase.s

# target to generate assembly for a file
src/frontend/parser/ParserBase.cpp.s:
	$(MAKE) -f CMakeFiles/modVer.dir/build.make CMakeFiles/modVer.dir/src/frontend/parser/ParserBase.cpp.s
.PHONY : src/frontend/parser/ParserBase.cpp.s

src/frontend/parser/TextPos.obj: src/frontend/parser/TextPos.cpp.obj

.PHONY : src/frontend/parser/TextPos.obj

# target to build an object file
src/frontend/parser/TextPos.cpp.obj:
	$(MAKE) -f CMakeFiles/modVer.dir/build.make CMakeFiles/modVer.dir/src/frontend/parser/TextPos.cpp.obj
.PHONY : src/frontend/parser/TextPos.cpp.obj

src/frontend/parser/TextPos.i: src/frontend/parser/TextPos.cpp.i

.PHONY : src/frontend/parser/TextPos.i

# target to preprocess a source file
src/frontend/parser/TextPos.cpp.i:
	$(MAKE) -f CMakeFiles/modVer.dir/build.make CMakeFiles/modVer.dir/src/frontend/parser/TextPos.cpp.i
.PHONY : src/frontend/parser/TextPos.cpp.i

src/frontend/parser/TextPos.s: src/frontend/parser/TextPos.cpp.s

.PHONY : src/frontend/parser/TextPos.s

# target to generate assembly for a file
src/frontend/parser/TextPos.cpp.s:
	$(MAKE) -f CMakeFiles/modVer.dir/build.make CMakeFiles/modVer.dir/src/frontend/parser/TextPos.cpp.s
.PHONY : src/frontend/parser/TextPos.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... modVer"
	@echo "... rebuild_cache"
	@echo "... src/common/Log.obj"
	@echo "... src/common/Log.i"
	@echo "... src/common/Log.s"
	@echo "... src/frontend/boogie/coco/Parser.obj"
	@echo "... src/frontend/boogie/coco/Parser.i"
	@echo "... src/frontend/boogie/coco/Parser.s"
	@echo "... src/frontend/boogie/coco/Scanner.obj"
	@echo "... src/frontend/boogie/coco/Scanner.i"
	@echo "... src/frontend/boogie/coco/Scanner.s"
	@echo "... src/frontend/parser/ParserBase.obj"
	@echo "... src/frontend/parser/ParserBase.i"
	@echo "... src/frontend/parser/ParserBase.s"
	@echo "... src/frontend/parser/TextPos.obj"
	@echo "... src/frontend/parser/TextPos.i"
	@echo "... src/frontend/parser/TextPos.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

